workflow:
  rules:
    - if: $GITLAB_USER_LOGIN == "taggart"
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - deploy

build:
  stage: build
  tags: [windows,csharp]
  script:
  - '& CiScripts\Scripts\build.ps1'
  artifacts:
    untracked: true
    when: always

release_job:
  stage: deploy
  tags: [windows,csharp]
  script:
  - $VERSION = (get-item -path .\source\fragmentlab\bin\anycpu\debug\net48\FragmentLab.exe).VersionInfo.ProductVersion
  - '& $MSBUILD_FULL_PATH -p:configuration=release -t:restore -p:RestorePackagesConfig=true /p:RestoreSources=$NUGET_SOURCE'
  - '& $MSBUILD_FULL_PATH -p:configuration=release'
  - Invoke-RestMethod -Headers @{ "JOB-TOKEN"="$CI_JOB_TOKEN"; "Content-Type"="multipart/form-data" } -InFile source/installer/bin/release/installer.msi -uri "https://bms-developer.science.uu.nl/api/v4/projects/99/packages/generic/FragmentLab/$VERSION/installer.msi" -Method put
  - git remote set-url origin git@bms-developer.science.uu.nl:csharp/shotgun/fragmentlab.git
  - git tag -a "$VERSION" -m $VERSION
  - git push origin $VERSION
  - mkdir release-cli
  - curl.exe -L https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-windows-amd64.exe --output release-cli\release-cli.exe
  - $cliDir = (Get-Item .).FullName+"\release-cli\"
  - '$env:Path += ";$cliDir"'
  - $env:asset = "{`"name`":`"Installer`",`"url`":`"https://bms-developer.science.uu.nl/api/v4/projects/99/packages/generic/FragmentLab/$VERSION/installer.msi`"}"
  - $env:assetjson = $env:asset | ConvertTo-Json
  - release-cli --insecure-https=true create --name "Release $VERSION" --description "Created using the release-cli $VERSION" --tag-name "$VERSION" --assets-link=$env:assetjson
  artifacts:
    untracked: true
    when: always

mirror:
  stage: deploy
  tags: [windows,csharp]
  script:
  - $VERSION = (get-item -path .\source\fragmentlab\bin\anycpu\debug\net48\FragmentLab.exe).VersionInfo.ProductVersion
  - '& $MSBUILD_FULL_PATH -p:configuration=release -t:restore -p:RestorePackagesConfig=true /p:RestoreSources=$NUGET_SOURCE'
  - '& $MSBUILD_FULL_PATH -p:configuration=release'
  - git remote set-url origin "https://$BASTIAAN_ACCESS@github.com/ScheltemaLab/FragmentLab""
  - git push origin $VERSION
  - git tag -a "$VERSION" -m $VERSION
  - git push origin $VERSION
  - gh release create $VERSION -t $VERSION -n $VERSION
  - gh release upload $VERSION source/installer/bin/release/installer.msi
  artifacts:
    untracked: true
    when: always
