workflow:
  rules:
    - if: $GITLAB_USER_LOGIN == "taggart"
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - deploy

build:
  stage: build
  tags: [windows,csharp]
  script:
  - '& CiScripts\Scripts\build.ps1'
  artifacts:
    untracked: true
    when: always

release_job:
  stage: deploy
  tags: [windows,csharp]
  script:
  - $VERSION = (get-item -path .\source\fragmentlab\bin\anycpu\debug\net472\FragmentLab.exe).VersionInfo.ProductVersion
  - '& $MSBUILD_FULL_PATH -p:configuration=release -t:restore -p:RestorePackagesConfig=true /p:RestoreSources=$NUGET_SOURCE'
  - '& $MSBUILD_FULL_PATH -p:configuration=release'
  - Invoke-RestMethod -Headers @{ "JOB-TOKEN"="$CI_JOB_TOKEN"; "Content-Type"="multipart/form-data" } -InFile source/installer/bin/release/installer.msi -uri "https://bms-developer.science.uu.nl/api/v4/projects/99/packages/generic/FragmentLab/$VERSION/installer.msi" -Method put
  - git remote set-url origin git@bms-developer.science.uu.nl:csharp/shotgun/fragmentlab.git
  - git tag -a "$VERSION" -m $VERSION
  - git push origin $VERSION
  - curl.exe -L https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-windows-amd64.exe --output release-cli.exe
  - $postParams = @{name='$VERSION';tag_name='$VERSION';description='$VERSION';ref='$CI_COMMIT_SHA'}
  - $headers = @{"PRIVATE-TOKEN"=$ACCESS_TOKEN};
  - Invoke-WebRequest -Uri "https://bms-developer.science.uu.nl/api/v4/projects/99/releases" -Method POST -Body $postParams -Headers $headers -UseBasicParsing
  #release:
  #  name: 'Release $VERSION'
  #  description: 'Created using the release-cli $VERSION'  
  #  tag_name: '$VERSION'                                       
  #  ref: '$CI_COMMIT_SHA'            
  #  assets:
  #    links:
  #      - name: 'installer'
  #        url: 'https://bms-developer.science.uu.nl/api/v4/projects/99/packages/generic/FragmentLab/$VERSION/installer.msi'
  artifacts:
    untracked: true
    when: always
