include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

workflow:
  rules:
    - if: $GITLAB_USER_LOGIN != "taggart"

stages:
  - build
  - deploy

build:
  stage: build
  tags: [windows,csharp]
  script:
  - '& CiScripts\Scripts\build.ps1'
  artifacts:
    untracked: true
    when: always

release:
  stage: deploy
  tags: [windows,csharp]
  script:
  - $MSBUILD_FULL_PATH source/installer
  artifacts:
    untracked: true
    when: always
